# Generated by Django 3.2.8 on 2021-10-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='job_seeker',
        ),
        migrations.RemoveField(
            model_name='account',
            name='recuiter',
        ),
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(blank=True, choices=[('job_seeker', 'job_seeker'), ('recuiter', 'recuiter')], max_length=20),
        ),
        migrations.AddField(
            model_name='job_seeker',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20),
        ),
    ]
