# Generated by Django 3.2.8 on 2021-10-23 16:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20211023_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_seeker',
            name='resume',
            field=models.FileField(blank=True, upload_to='job_seeker_resume', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='job_seeker',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_seeker_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
