# Generated by Django 3.2.8 on 2021-10-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_job_seeker_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_seeker',
            name='min_salary',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
