# Generated by Django 3.2.8 on 2021-10-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_job_seeker_min_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recuiter',
            old_name='name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='recuiter',
            old_name='location',
            new_name='current_location',
        ),
        migrations.AddField(
            model_name='recuiter',
            name='employment_state',
            field=models.CharField(blank=True, choices=[('Hiring', 'Hiring'), ('Firing', 'Firing'), ('Freeze Mode', 'Freeze Mode'), ('Laying Off', 'Laying Off')], max_length=100),
        ),
    ]
