# Generated by Django 3.2.8 on 2021-10-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20211023_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recuiter',
            name='website',
            field=models.URLField(blank=True, default='http://'),
        ),
    ]
