# Generated by Django 3.2.8 on 2021-10-24 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_recuiter_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='recuiter',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='passwordresetcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
