# Generated by Django 3.2.8 on 2021-10-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20211024_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recuiter',
            name='website',
            field=models.URLField(blank=True, default='https://'),
        ),
    ]
