# Generated by Django 3.2.9 on 2021-12-06 21:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20211206_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
