# Generated by Django 3.2.9 on 2021-11-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_seeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='job_seeker_image')),
                ('resume', models.FileField(upload_to='resume_file')),
                ('current_location', models.CharField(max_length=300)),
                ('bio', models.TextField()),
            ],
        ),
    ]
