# Generated by Django 3.2.9 on 2021-11-12 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_job_seeker_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_seeker',
            name='resume',
            field=models.FileField(upload_to='resume_file', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
