# Generated by Django 3.2.9 on 2021-11-18 21:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_job_seeker_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_seeker',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job_seeker',
            name='current_location',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='job_seeker',
            name='image',
            field=models.ImageField(blank=True, upload_to='job_seeker_image'),
        ),
        migrations.AlterField(
            model_name='job_seeker',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='job_seeker',
            name='resume',
            field=models.FileField(blank=True, upload_to='resume_file', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='job_seeker',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='company_logo',
            field=models.ImageField(blank=True, upload_to='company_logo'),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='company_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
