# Generated by Django 3.2.8 on 2021-10-30 10:25

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone
import django_resized.forms
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('date_published', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('date_created', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, quality=0, size=[750, 375], upload_to='article_pics')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('slug', models.SlugField(blank=True)),
                ('status', models.CharField(choices=[('Drafted', 'Drafted'), ('Published', 'Published')], default='DRAFT', max_length=20)),
                ('count_words', models.CharField(blank=True, default=0, max_length=50)),
                ('read_time', models.CharField(blank=True, default=0, max_length=50)),
                ('deleted', models.BooleanField(blank=True, default=False)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'blogs',
                'ordering': ('-date_published',),
            },
        ),
    ]
