# Generated by Django 3.2.8 on 2021-10-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
