# Generated by Django 3.2.8 on 2021-10-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('job_nature', models.CharField(choices=[('Part Time', 'Part Time'), ('Full Time', 'Full Time')], max_length=25)),
                ('application_link', models.URLField(blank=True, default='https://')),
                ('application_email', models.EmailField(blank=True, max_length=254)),
                ('salary_range', models.CharField(help_text='e.g $500 - $900', max_length=200)),
                ('application_deadline', models.DateField(blank=True)),
                ('slot_available', models.PositiveIntegerField(default=1)),
                ('Knowledge_skills_abilities', models.TextField(blank=True, help_text='End each input with comma e.g System Software Development,Strong problem solving and debugging skills')),
                ('education_experience', models.TextField(blank=True, help_text='End each input with comma e.g 3 or more years of professional design experience,Direct response email experience')),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
