# Generated by Django 3.2.8 on 2021-10-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Graphic Design', 'Graphic Design')], default='Web Development', max_length=255),
        ),
    ]
