# Generated by Django 3.2.8 on 2021-10-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='flaticon',
            field=models.ImageField(null=True, upload_to='flat Icons'),
        ),
    ]
