# Generated by Django 3.2.8 on 2021-10-25 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_category_flaticon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='flaticon',
            field=models.CharField(blank=True, default='flaticon-tour', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[], max_length=255),
        ),
    ]
