# Generated by Django 3.2.8 on 2021-10-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20211025_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='flaticon',
            field=models.ImageField(null=True, upload_to='flat Icons'),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Graphic Design', 'Graphic Design'), ('Others', 'Others')], default='Web Development', max_length=255),
        ),
    ]
