# Generated by Django 3.2.8 on 2021-10-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20211025_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='flaticon',
            field=models.CharField(blank=True, default='flaticon', max_length=250),
            preserve_default=False,
        ),
    ]
