# Generated by Django 3.2.8 on 2021-10-25 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_auto_20211025_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
