# Generated by Django 3.2.8 on 2021-10-25 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_alter_job_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
