# Generated by Django 3.2.8 on 2021-10-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_job_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Knowledge_skills_abilities',
            field=models.TextField(blank=True, help_text='End each input with comma e.g System Software Development,Strong problem solving and debugging skills', null=True),
        ),
    ]
