# Generated by Django 3.2.8 on 2021-10-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_alter_job_knowledge_skills_abilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Knowledge_skills_abilities',
            field=models.TextField(blank=True, default='Python', help_text='End each input with comma e.g System Software Development,Strong problem solving and debugging skills'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='job_nature',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=25),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_range',
            field=models.PositiveIntegerField(),
        ),
    ]
