# Generated by Django 3.2.8 on 2021-10-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_auto_20211029_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='confirmed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
