# Generated by Django 3.2.8 on 2021-10-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_job_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='confirmed',
            field=models.BooleanField(blank=True),
        ),
    ]
